module.exports = {
    testEnvironment: 'node',
    verbose: true,
    clearMocks: true,
    testMatch: ['**/test/**/*.{test,spec}.js'],
    collectCoverage: true,
    collectCoverageFrom: [
        '!**/node_modules/**',
        '!**/tests/**',
        '!**/migrations/**',
        '!**/seeders/**',
        '!**/config/**',
        '!**/index.js',
    ],
    coverageDirectory: 'coverage',
    reporters: ['default'],
    resetModules: true,
    transform: {},
    testTimeout: 10000,
};
